# Top-level key, which contains configurations for all app containers.
applications:
  # The app's name, which must be unique within the project.
  kestra:
    type: 'java:21'
    web:
      commands:
        start: ./kestra-0.18.5 server standalone --config kestra.yaml --port=8888
    hooks:
      build: |
        curl -L -o kestra.zip https://api.kestra.io/v1/versions/download
        unzip kestra.zip
routes:
    "https://{default}/":
        type: upstream
        upstream: kestra:http