applications:
  # The app's name, which must be unique within the project.
  kestra:
    type: 'java:21'
    web:
      commands:
        start: bin/kestra-latest server standalone --config ./kestra.yaml --port=$PORT
    mounts:
      kestra-storage:
        source: storage
        source_path: kestra-storage

services:
  postgresql:
    type: postgresql:16

routes:
  "https://{default}/ui/":
    type: upstream
    upstream: kestra:http